### ISSUE TITLE
Seed db with dummy data via a script (keep these in a new repo?)

### ISSUE THREAD

**Issue by broneks** [minimalchat/daemon#16] opened 2017-03-17 23:57 UTC
operators
clients
chats
messages

**Comment by mihok** [comment] 2017-03-18 00:44
This could also be put into the Makefile using template files + curl

**Comment by teesloane** [comment] 2017-03-18 02:07
I feel like this should just be written in the project in a .go file no? Just make an external file that creates dummy data as the operator project does too. We could just do a environment variable check for `development` and if so, store some dummy chats in memory to respond with on GET requests.

**Comment by broneks** [comment] 2017-03-19 01:04
Keeping it external from the source code is more versatile. A makefile for example could be passed arguments saying which seed to use (in case we have different data covering different scenarios). Also once we have a database it makes more sense to import data via command line than from within the app.

**Comment by teesloane** [comment] 2017-03-19 01:42
that's true, that makes more sense. So this will automate putting the data into memory through a series of post requests I suppose? 

either way, you've got me on board.

**Comment by mihok** [comment] 2017-03-19 16:16
So I started tryng to tackle this issue and realized that because the API (by design) doesnt allow full CRUD (specifically Create) of Chats, Clients, or Operators, generating this data outside of the codebase is a little difficult.

**Comment by mihok** [comment] 2017-07-08 14:09
Closing this for now

**Closed as completed by mihok** 2017-07-08 14:09 UTC
